
trigger: none

pool: Default

resources:
- repo: self

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub Service Conn'
        repository: 'rahulkrajput/kubernetes'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'nginx-v5'