# Deploy Kubernetes Deployment On AKS Cluster Pipeline

trigger:
 
 paths:
   include:
     - Pipelines/02-Deploy-Kubernetes-Deployment-On-AKS-Cluster-Pipeline.yml

pool: Default
  
# Deploy Nginx App On Cluster
# Stage-01: Deploy Nginx App Deployment
# Stage-02: Deploy Nginx App Service (LoadBalancer)
# Stage-03: When you want Delete Nginx App then Uncomment "delete task" and the re-run pipeline.  



stages: 

# Stage-01
- stage: DeployNginxAppDeployment
  jobs: 
    - job: DeployNginxAppDeployment
      pool: Default
      steps:
        - task: KubernetesManifest@1
          displayName: Nginx App Deployment
          inputs:
            action: 'deploy'
            connectionType: 'azureResourceManager'
            azureSubscriptionConnection: 'terraform-aks-cluster-svc-conn'
            azureResourceGroup: 'terraform-aks-prod'
            kubernetesCluster: 'terraform-aks-prod-cluster'
            useClusterAdmin: true
            namespace: 'default'
            manifests: 'kubernetes-cluster-manifests/01-Webserver-Apps/01-NginxApp1-Deployment.yml'

# Stage-02
- stage: DeployNginxAppService
  jobs: 
    - job: DeployNginxAppService
      pool: Default
      steps:
        - task: KubernetesManifest@1
          displayName: Nginx App Service
          inputs:
            action: 'deploy'
            connectionType: 'azureResourceManager'
            azureSubscriptionConnection: 'terraform-aks-cluster-svc-conn'
            azureResourceGroup: 'terraform-aks-prod'
            kubernetesCluster: 'terraform-aks-prod-cluster'
            useClusterAdmin: true
            namespace: 'default'
            manifests: 'kubernetes-cluster-manifests/01-Webserver-Apps/02-NginxApp1-LoadBalancer-Service.yml'



# When you want Delete Nginx App then Uncomment "delete task" and the re-run pipeline.  


# Stage-03
# - stage: DeleteNginxApp
#   jobs: 
#     - job: DeleteNginxApp
#       pool: Default
#       steps:
#       - task: KubernetesManifest@1
#         displayName: Delete Nginx App 
#         inputs:
#           action: 'delete'
#           connectionType: 'azureResourceManager'
#           azureSubscriptionConnection: 'terraform-aks-cluster-svc-conn'
#           azureResourceGroup: 'terraform-aks-prod'
#           kubernetesCluster: 'terraform-aks-prod-cluster'
#           useClusterAdmin: true
#           namespace: 'default'
#           arguments: '-f kubernetes-cluster-manifests/01-Webserver-Apps/'
        